steps:

  - command:  |
      bash .scripts/artifactory.sh
      gradle assemble artifactoryPublish
    label: "Build Library"
    agents:
      - "queue=automation-android-builder-fleet"

  - command:  |
      bash .scripts/artifactory.sh
      gradle test
    label: "Run Tests"
    agents:
      - "queue=automation-android-builder-fleet"
  - wait

  - command: "echo 'Success!!'"
    label: ":trophy: Success"
    agents:
      - "queue=automation-android-builder-fleet"
